AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cutz & Fadez: Observability Layer (GuardDuty, SNS, EventBridge) - Compliant with Sec 4.5, 7.5, 8.7'
 
Resources:
  # 1. GuardDuty Detector (The Threat Radar)
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: FIFTEEN_MINUTES
 
  # 2. SNS Topic (The Alarm System)
  SecurityAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "CutzFadez-Security-Alerts-${AWS::StackName}"
      DisplayName: "Cutz & Fadez Security Operations"
 
  # 3. EventBridge Rule (The Automation Wire)
  # Compliance: Section 8.7 Automated Recovery & 7.5 GuardDuty Automation
  GuardDutyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "CutzFadez-GuardDuty-Rule-${AWS::StackName}"
      Description: "Trigger SNS when GuardDuty finds a High Severity threat"
      EventPattern:
        source:
          - "aws.guardduty"
        detail-type:
          - "GuardDuty Finding"
        detail:
          severity: [ 7, 8, 8.0, 8.9 ] # Only alert on High Severity threats
      State: "ENABLED"
      Targets:
        - Arn: !Ref SecurityAlertsTopic
          Id: "GuardDutySNS"
 
  # 4. SNS Permission (Allow EventBridge to ring the alarm)
  SnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SecurityAlertsTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowEventBridgeToPublish
            Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Action: "sns:Publish"
            Resource: !Ref SecurityAlertsTopic
 
Outputs:
  GuardDutyId:
    Value: !Ref GuardDutyDetector
    Description: "The ID of the GuardDuty Detector"
  SnsTopicArn:
    Value: !Ref SecurityAlertsTopic
    Description: "The ARN of the Security Alerts SNS Topic"