AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cutz & Fadez: Lab 3 - Backend Layer'
 
Resources:
  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CutzFZ-Products
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - {AttributeName: category, AttributeType: S}
        - {AttributeName: sku, AttributeType: S}
      KeySchema:
        - {AttributeName: category, KeyType: HASH}
        - {AttributeName: sku, KeyType: RANGE}
 
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: [{Effect: Allow, Principal: {Service: lambda.amazonaws.com}, Action: sts:AssumeRole}]
      Policies:
        - PolicyName: DBRead
          PolicyDocument:
            Version: '2012-10-17'
            Statement: [{Effect: Allow, Action: [dynamodb:Scan], Resource: !GetAtt ProductTable.Arn}]
 
  GetProductsFunc:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CutzFZ-GetProducts
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Environment: {Variables: {TABLE_NAME: !Ref ProductTable}}
      Code:
        ZipFile: |
          const { DynamoDBClient, ScanCommand } = require("@aws-sdk/client-dynamodb");
          const client = new DynamoDBClient({});
          exports.handler = async (event) => {
            const command = new ScanCommand({ TableName: process.env.TABLE_NAME });
            const data = await client.send(command);
            return { statusCode: 200, body: JSON.stringify(data.Items) };
          };
 
  LambdaUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref GetProductsFunc
      AuthType: NONE
      Cors: {AllowOrigins: ["*"], AllowMethods: ["GET"]}
 
  LambdaPerm:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetProductsFunc
      Principal: "*"
      Action: lambda:InvokeFunctionUrl
      FunctionUrlAuthType: NONE
 
Outputs:
  ApiUrl: {Value: !GetAtt LambdaUrl.FunctionUrl}