AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cutz & Fadez: Encryption Layer (KMS) - Compliant with Sec 5.3'
 
Resources:
  # 1. The Master Key (CMK)
  CutzFadezKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Master Encryption Key for Cutz & Fadez Zero Trust Data"
      Enabled: true
      EnableKeyRotation: true # Compliance: Section 5.3 (Auto Rotation)
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: Allow CloudWatch Logs
            Effect: Allow
            Principal:
              Service: "logs.us-east-2.amazonaws.com"
            Action: 
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource: "*"
 
  # 2. The Alias (A friendly name to find it easily)
  KeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/cutz-fadez-master-key
      TargetKeyId: !Ref CutzFadezKey
 
Outputs:
  KeyArn:
    Value: !GetAtt CutzFadezKey.Arn
    Description: "The ARN of the Master Key"